name: CI - Stateful Application Instances
on:
  pull_request:
    paths:
    - 'samples/autoscaling-over-time-dashboard/**'
  
jobs:
  solution:
    name: Runtime (Solution)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Solution
      run: dotnet build ./samples/autoscaling-over-time-dashboard/src/AzureAutoscalingToolbox.Samples.sln --configuration Release